### ISSUE TITLE
Improve script loading

### ISSUE THREAD

**Issue by santiq** [koole/gatsby-plugin-hotjar-tracking#5]
Hi there!

Thanks for this fork, it seems more updated and maintained than the source.

I was wondering if you could add `async` or `defer` to the script in order to improve page load speed?

Here is an example of what I'm talking about: https://benmarshall.me/how-to-load-3rd-party-javascript-efficiently/

**Comment by koole** [comment]
Great idea! I think it would be best to add this an optional setting to enable either `async` or `defer` as to not change the plugins default behaviour when people update to the new version.

I'll see if I can make some time to add this feature soon.

**Comment by koole** [comment]
After taking a look at this I noticed Hotjar script already creates its script tags with an async attribute:
```html
<script async="" src="https://static.hotjar.com/c/hotjar-XXXXXXX.js?sv=6"></script>
```

I don't think adding async or defer to the script we inject wouldn't be useful because of this. It wouldn't noticeably impact performance, but you would lose [the advantages](https://help.hotjar.com/hc/en-us/articles/115011639927-What-is-the-Hotjar-Tracking-Code-) of having the Hotjar Tracking Code loading right away, like tracking events before the external script has been loaded.
